-- ════════════════════════════════════════════════════════════════════════════
-- ClinSync — upload + ingest merge · PostgreSQL 15+
-- Follows the LLD data model: M1 organization tables, M2.1 upload and library
-- tables, M2.5 state machines, M3.2 document_specialty.
--
-- Markers used below:
--   [LLD]      exactly as the LLD defines it
--   [POC]      added by the Ingest Worker POC — needed for claim, resume, retry;
--              to be folded back into the LLD
--   [Anugrah]  needed by the File Upload POC's API
--   [deferred] in the LLD, but out of this merge's scope — created, unused
--
-- Primary keys are UUID throughout, per OD-18's recommendation.
-- Reference masters (specialty, document_type) stay BIGINT, as the LLD has them.
-- ════════════════════════════════════════════════════════════════════════════

CREATE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;                                             -- [LLD]


-- ── M1 · Organizations ──────────────────────────────────────────────────────
-- Auth is out of scope, but every organization_id is a foreign key into this
-- table, so it exists and holds the one POC organization.

CREATE TABLE organizations (                                     -- [LLD]
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name        VARCHAR     NOT NULL UNIQUE,
  is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_org_updated BEFORE UPDATE ON organizations
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO organizations (id, name)                             -- POC seed: POC_ORGANIZATION_ID
VALUES ('00000000-0000-4000-8000-000000000001', 'Mytonomy (POC)');

-- organization_config and organization_memberships: [deferred] with auth.


-- ── Reference masters ───────────────────────────────────────────────────────

CREATE TABLE specialty (                                         -- [LLD] [deferred]
  specialty_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          VARCHAR(64)  NOT NULL UNIQUE,
  display_name  VARCHAR(255) NOT NULL,
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE document_type (                                     -- [LLD] [deferred]
  document_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code             VARCHAR(64)  NOT NULL UNIQUE,
  display_name     VARCHAR(255) NOT NULL,
  is_active        BOOLEAN      NOT NULL DEFAULT TRUE
);

-- organization_specialty and organization_document_type: [deferred] with metadata tagging.


-- ── M2 · The library ────────────────────────────────────────────────────────
-- Created before the upload tables, because upload_file.replaces_document_id
-- and staged_document.duplicate_of_document_id point here. The reverse link,
-- documents.source_file_id, is added once upload_file exists (bottom of file).

CREATE TABLE documents (                                         -- [LLD]
  document_id          UUID         PRIMARY KEY,                 -- uuid5 of the candidate: a re-run commit reuses it
  organization_id      UUID         NOT NULL REFERENCES organizations(id),
  title                VARCHAR(512) NOT NULL,
  title_norm           VARCHAR(512) NOT NULL,                    -- lower-cased, punctuation-stripped
  file_name            VARCHAR(512) NOT NULL,                    -- original name of the current version
  file_name_norm       VARCHAR(512) NOT NULL,                    -- casefolded, trimmed — the name+size check
  document_type_id     BIGINT       REFERENCES document_type(document_type_id),   -- [deferred] null = untagged
  current_version      INTEGER      NOT NULL DEFAULT 1,          -- replace is out of scope: always 1 here
  s3_key               VARCHAR(1024) NOT NULL,                   -- ClinSync/processed/{org}/{document_id}/v{n}_{file_name}
  file_ext             VARCHAR(10)  NOT NULL,
  size_bytes           BIGINT       NOT NULL,
  content_hash         CHAR(64)     NOT NULL,                    -- SHA-256, computed by the worker
  source_file_id       UUID,                                     -- FK added below; provenance only
  video_script_seq     INTEGER,
  status               VARCHAR(16)  NOT NULL DEFAULT 'active'
                         CHECK (status IN ('active', 'archived')),
  added_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
  version_uploaded_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  version_uploaded_by  BIGINT       NOT NULL,                    -- AUTH user id; POC_USER_ID until auth exists
  last_scanned_at      TIMESTAMPTZ,                              -- [deferred] scan
  last_scan_id         UUID,                                     -- [deferred] FK to scan_run when M3 lands
  highest_risk         VARCHAR(16)
                         CHECK (highest_risk IN ('HIGH', 'MEDIUM', 'LOW', 'CONFIRMATORY')),
  open_findings        INTEGER      NOT NULL DEFAULT 0,
  CONSTRAINT uq_org_title UNIQUE (organization_id, title_norm)
);
CREATE INDEX idx_doc_org_hash      ON documents (organization_id, content_hash);
CREATE INDEX idx_doc_org_filename  ON documents (organization_id, file_name_norm);
CREATE INDEX idx_doc_org_scanned   ON documents (organization_id, last_scanned_at);
CREATE TRIGGER trg_doc_updated BEFORE UPDATE ON documents
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE document_specialty (                                -- [LLD M3.2] [deferred]
  document_id   UUID   NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
  specialty_id  BIGINT NOT NULL REFERENCES specialty(specialty_id),
  PRIMARY KEY (document_id, specialty_id)
);

-- document_version_log: [deferred] with replace.


-- ── M2 · Upload and ingest ──────────────────────────────────────────────────

CREATE TABLE upload_batch (                                      -- [LLD]
  batch_id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  UUID        NOT NULL REFERENCES organizations(id),
  created_by       BIGINT      NOT NULL,                         -- AUTH user id; POC_USER_ID until auth exists
  status           VARCHAR(16) NOT NULL DEFAULT 'in_progress'
                     CHECK (status IN ('in_progress', 'staged', 'committed', 'abandoned')),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_batch_org ON upload_batch (organization_id, batch_id);


CREATE TABLE upload_file (                                       -- transfers only: one row per object the browser sent
  file_id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),       -- [LLD]
  batch_id             UUID          NOT NULL REFERENCES upload_batch(batch_id) ON DELETE CASCADE,
  organization_id      UUID          NOT NULL REFERENCES organizations(id),
  client_ref           VARCHAR(64)   NOT NULL DEFAULT gen_random_uuid()::text,  -- [LLD] server-generated when the client sends none
  file_name            VARCHAR(512)  NOT NULL,
  file_ext             VARCHAR(10)   NOT NULL,
  size_bytes           BIGINT        NOT NULL,
  content_type         VARCHAR(128),                                               -- [Anugrah] passed to the multipart upload
  content_hash         CHAR(64),                                                   -- [LLD] from the browser if sent; the worker's hash lives on the candidate
  s3_key               VARCHAR(1024) NOT NULL,                                     -- always ClinSync/incoming/…
  upload_id            VARCHAR(255),                                               -- [LLD] S3's multipart id — Anugrah's "uploadId"
  is_archive           BOOLEAN       NOT NULL,
  intent               VARCHAR(16)   NOT NULL DEFAULT 'new'
                         CHECK (intent IN ('new', 'replace')),                    -- [LLD] replace [deferred]
  replaces_document_id UUID          REFERENCES documents(document_id),
  detected_type        VARCHAR(32),                                                -- [LLD] what the bytes really are
  status               VARCHAR(16)   NOT NULL DEFAULT 'staged'
                         CHECK (status IN ('staged', 'uploading', 'uploaded', 'processing',
                                           'processed', 'partial', 'rejected', 'error')),  -- [LLD M2.5]
  status_message       VARCHAR(512),
  entries_total        INTEGER,
  entries_done         INTEGER       NOT NULL DEFAULT 0,
  attempt_count        INTEGER       NOT NULL DEFAULT 0,                           -- [POC] bounds retries
  claim_token          UUID,                                                       -- [POC] fences every worker write
  heartbeat_at         TIMESTAMPTZ,                                                -- [POC] stale detection
  uploaded_at          TIMESTAMPTZ,                                                -- [POC] reconcile sweeper
  created_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
  CONSTRAINT chk_replace_target CHECK (                                            -- [LLD]
    (intent = 'new'     AND replaces_document_id IS NULL) OR
    (intent = 'replace' AND replaces_document_id IS NOT NULL AND is_archive = FALSE)),
  CONSTRAINT uq_batch_client_ref UNIQUE (batch_id, client_ref),                    -- [LLD]
  CONSTRAINT uq_upload_id        UNIQUE (upload_id)                                -- [Anugrah] presign/abort look up by it
);
CREATE INDEX idx_file_batch     ON upload_file (batch_id);
CREATE INDEX idx_file_sweep     ON upload_file (status, heartbeat_at);            -- [POC]
CREATE INDEX idx_file_reconcile ON upload_file (status, uploaded_at);             -- [POC]
CREATE INDEX idx_file_stale     ON upload_file (status, created_at);              -- stale-upload sweeper
CREATE TRIGGER trg_file_updated BEFORE UPDATE ON upload_file
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();


CREATE TABLE staged_document (                                   -- candidates; deleted on commit
  staged_id                  UUID          PRIMARY KEY DEFAULT gen_random_uuid(),  -- [LLD]
  batch_id                   UUID          NOT NULL REFERENCES upload_batch(batch_id) ON DELETE CASCADE,
  organization_id            UUID          NOT NULL REFERENCES organizations(id),
  source_file_id             UUID          NOT NULL REFERENCES upload_file(file_id) ON DELETE CASCADE,
  source_entry_name          VARCHAR(1024),                                          -- null = direct upload
  entry_index                INTEGER,                                                -- [POC] position among file entries — deterministic staging keys
  file_name                  VARCHAR(512)  NOT NULL,
  file_ext                   VARCHAR(10)   NOT NULL,
  size_bytes                 BIGINT,
  content_hash               CHAR(64),                                               -- worker-computed SHA-256
  s3_key                     VARCHAR(1024),                                          -- ClinSync/staging/…; null when rejected
  status                     VARCHAR(16)   NOT NULL CHECK (status IN ('processed', 'rejected')),
  reject_reason              VARCHAR(512),
  proposed_title             VARCHAR(512),                                           -- file name stem in this merge
  confirmed_title            VARCHAR(512),                                           -- set = proposed at commit, while metadata is out of scope
  title_norm                 VARCHAR(512),
  proposed_document_type_id  BIGINT        REFERENCES document_type(document_type_id),   -- [deferred]
  confirmed_document_type_id BIGINT        REFERENCES document_type(document_type_id),   -- [deferred]
  duplicate_of_document_id   UUID          REFERENCES documents(document_id),
  duplicate_kind             VARCHAR(20)
                               CHECK (duplicate_kind IN ('replace_requested', 'same_title',
                                                         'same_content')),          -- same_content: [POC] addition — byte-identical file
  resolution                 VARCHAR(20)   NOT NULL DEFAULT 'pending'
                               CHECK (resolution IN ('pending', 'create_new',
                                                     'replace_existing', 'discard')),
  video_script_seq           INTEGER,
  created_at                 TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at                 TIMESTAMPTZ   NOT NULL DEFAULT now(),
  CONSTRAINT uq_entry UNIQUE NULLS NOT DISTINCT                                      -- [LLD] the resume / upsert key
    (source_file_id, source_entry_name, video_script_seq)
);
CREATE INDEX idx_staged_batch_status ON staged_document (batch_id, status);
CREATE TRIGGER trg_staged_updated BEFORE UPDATE ON staged_document
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ── Audit ───────────────────────────────────────────────────────────────────

CREATE TABLE audit_log (                                         -- [LLD]
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  UUID        REFERENCES organizations(id),
  user_id          BIGINT      NOT NULL,                         -- POC_USER_ID (0, the system actor — OD-19)
  action           VARCHAR     NOT NULL,                         -- this merge writes: batch_committed
  entity_type      VARCHAR,
  entity_id        VARCHAR,
  details          JSONB       NOT NULL DEFAULT '{}',
  request_id       VARCHAR,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_org_time ON audit_log (organization_id, created_at);


-- ── Links that close a cycle ────────────────────────────────────────────────
-- documents ↔ upload_file reference each other. SET NULL, because abandoning a
-- batch deletes its files, and a library document must survive that.

ALTER TABLE documents
  ADD CONSTRAINT fk_doc_source_file
  FOREIGN KEY (source_file_id) REFERENCES upload_file(file_id) ON DELETE SET NULL;
